### ISSUE TITLE
Cross-platform support

### ISSUE THREAD

**Issue by IgorPolyakov** [tusur-coex/coex-plugin-task-skype#6]
module should work for windows and linux

**Comment by sea5kg** [comment]
Please remove suffix "win" from reponame)

**Comment by IgorPolyakov** [comment]
Yeap! I remove it)

**Comment by IgorPolyakov** [comment]
I need to test on the input data, and to close the issues

**Comment by sea5kg** [comment]
I have skype on my PC. I try it now

**Comment by sea5kg** [comment]
$ ./bin/coex-skype --input-folder / --output-folder ~/coex.output

===============TaskSkypeWin================

Debug mode ON

InputFolder:  "/" 

 :: /home/sea-kg/develop/tusur-coex/coex-testdata/Windows7_Ult/Users/UserVlad/AppData/Roaming/Skype/fox.user.3/main.dbConnected!
