### ISSUE TITLE
Failed xml format

### ISSUE THREAD

**Issue by sea5kg** [tusur-coex/coex-plugin-task-skype#9]
Duplicated lines in accounts.xml and *.xml

```
 <?xml version="1.0" encoding="UTF-8"?>
 <add>
 ....
 <?xml version="1.0" encoding="UTF-8"?>
 <add>
 ....
```

Steps for reproduce:
1. call first coex-skype
2. When first will be finised try run again

**Comment by IgorPolyakov** [comment]
https://github.com/tusur-coex/coex-plugin-task-skype/commit/a8b66f81ff65c6976449981904b1dcc18c7e13e6
